# https://taskfile.dev

version: "2"

tasks:
  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - pre-commit install
      - pre-commit run -a

  test:
    desc: Run automated tests
    cmds:
      - echo "N/A"

  secure:
    desc: Run automated security checks
    cmds:
      - echo "N/A"
